services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./storage:/app/storage
        ports:
            - 9000:8080
        depends_on:
            database_mysql:
                condition: service_healthy
    database_mysql:
        container_name: database_mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u laravel -psecret || exit 1"]
            interval: 3s    # Check every x seconds
            timeout: 2s     # Timeout if it takes longer than x  seconds
            retries: 5      # Mark unhealthy after 3 consecutive failures
volumes:
    db-data:
